Cp UI refractor
ucsb-cs156-s24/proj-happycows-s24-4pm-8 pull request #13
Opened 2024-05-20 22:14 UTC by charlene-patenaude

## Overview

In this PR, Emily and Charlene added new fonts to the HomePage and Navbar to make it fit the theme of the website. We also adjusted the color on the animated-text to be a smooth transition instead of a harsh one. 

## Screenshots (Optional)
![image](https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-8/assets/97643638/c2910448-7bba-45e3-8e76-4bf503e5a4db)

## Feedback Request (Optional)
Please give suggestions on the following:
- We are unsure about keeping the text animation seen in picture above - Currently it is an alternating rainbow/tomato (Emily) and we are unsure if it meshes well with the rest of the page/font 
- We are also considering removing the white boxes around the text but would like feedback

## Future Possibilities (Optional)
Some possible points could be:
- We would like to edit other UI elements on the project like the leaderboard and the stats but are pending approval from staff.

## Validation (Optional)
1. git fetch 
2. git checkout cp-UIRefractor
3. npm run storybook
4. check HomePage 

## Tests
NO Additional tests required
- [X] Frontend Unit tests (`npm test`) pass
- [X] Frontend Test coverage (`npm run coverage`) 100%
- [X] Frontend Mutation tests (`npx stryker run`) 100% 
- [X] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues
Closes #9

2024-05-22 00:02 UTC, Jumshim approved these changes
~~Wow! Looks super good :)~~

~~LGTM!~~

2024-05-22 00:26 UTC, Jumshim requested changes

2024-05-22 00:26 UTC, Jumshim commented on frontend/src/main/pages/HomePage.css
> +.reg-text
⛏️ I tried Ctrl+F'ing this section, and it doesn't seem like this CSS portion is used. Maybe take it out if it doesn't affect anything?

2024-05-22 02:14 UTC, Jumshim commented
LGTM!

2024-05-22 05:33 UTC, Jumshim approved these changes

2024-05-22 23:22 UTC, AnikaArora requested changes
Please link your dokku deployment so we can test it! Everything else looks good so far.

2024-05-22 23:51 UTC, AnikaArora requested changes, later dismissed
So it seems like you switched the boxes for join commons and visit commons. I think we should keep visit commons on the left and join commons on the right, unless you have a specific reason why you made that switch.

2024-05-22 23:53 UTC, charlene-patenaude commented
> So it seems like you switched the boxes for join commons and visit commons. I think we should keep visit commons on the left and join commons on the right, unless you have a specific reason why you made that switch.

We did that because it makes more sense to move right to left like when we read. We felt as though it had a better flow than before.

2024-05-23 05:26 UTC, pconrad approved these changes
LGTM

2024-05-23 05:27 UTC, merged