va - added announcements create page and basic test for it
ucsb-cs156-s24/proj-happycows-s24-4pm-8 pull request #35
Opened 2024-05-29 01:59 UTC by vaaniarora

## Overview

In this PR, (insert a brief description of what this PR enables for the end user as well as coders. If this placeholder text is still in place, this PR is not yet ready for review).

## Screenshots (Optional)

![Generic placeholder image](https://picsum.photos/640/480)

## Feedback Request (Optional)

Please give suggestions on the following:
- This method might not be the best way to do things. What do you think?
- The way this is implemented is the best I can think of. Is it acceptable?
- Where should these things go? I put them here, but it feels out of place.

## Future Possibilities (Optional)

Some possible points could be:
- This is the beginning/part of (insert feature).
- We can extend this to add (something beyond current functions).
- This can make things easier to (insert project).

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Go to this page.
4. Test this function.

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #0

2024-05-29 19:21 UTC, emilythai approved these changes, later dismissed
LGTM!

2024-05-30 00:56 UTC, pconrad requested changes
One small change to request then this is mergeable

2024-05-30 00:56 UTC, pconrad commented on frontend/src/main/pages/AdminCreateAnnouncementsPage.js
> +                <h1>Create Announcement</h1>
```suggestion
                <h1>Create Announcement</h1>
                <h2>Not implemented yet; coming soon!</h2>
```

2024-05-30 01:05 UTC, pconrad approved these changes
LGTM

2024-05-30 01:05 UTC, merged